server:
  port: 9999
spring:
  application:
    name: Pharos-DB-Connector
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: postgres
    password: Q1.w2-e3.r4
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        default_schema: PHAROS
    show-sql: true
