server:
  port: 9999
spring:
  application:
    name: Pharos-DB-Connector
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Q1.w2-e3.r4
    username: root
    url: jdbc:mysql://localhost:5555/PHAROS

logging:
  level:
    org:
      springframework:
        web: trace
      hibernate: trace
    com:
      pharos:
        dbconnector: trace


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9990/eureka
    instance:
      hostname: localhost